---
- name: Ansible Install Jenkins on Ubuntu 22.04 Server
  gather_facts: false
  hosts: all
  tasks:

    - name: Check Hostname
      command: hostname
      register: hname

    - debug: msg="{{ hname.stdout }}"

    
    - name: APT upgrade apt packages
      become: true
      apt:
        upgrade: "yes"
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Add Docker GPG apt Key
      become: true
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      become: true
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      become: true
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      become: true
      pip:
        name: docker

    - name: Install Java
      become: true
      apt:
        name: openjdk-11-jdk
        state: present

    - name: Add the Jenkins public GPG key to the apt repo
      become: true
      apt_key: 
        url : http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key
        state: present

    - name: Add Jenkins apt repo to the trusted sources list
      become: true
      apt_repository:
        repo: 'deb http://pkg.jenkins-ci.org/debian binary/'
        state: present

    - name: Install Jenkins
      become: true
      apt: 
        name: jenkins
        update_cache: yes
        install_recommends: no

    - name: Wait for Jenkins to start up
      wait_for: timeout=35

    - name: Get Jenkins password
      shell: cat /var/lib/jenkins/secrets/initialAdminPassword
      changed_when: false
      register: result

    - name: Password to "Unlock Jenkins"
      debug:
        var: result.stdout
